const ECONOMY_TEAM_TYPES = {
  ON_LOAD_DATAS: "ON_LOAD_DATAS",
  SUCCESFUL_FETCH: "SUCCESFUL_FETCH",
  SET_IS_PAYMENT: "SET_IS_PAYMENT",
  ADD_COST: "ADD_COST",
};

export default ECONOMY_TEAM_TYPES;
